name: Deploy Spring Boot Serverless App

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build layer dependencies
        run: |
          cd layers/spring-layer
          mvn clean package
          cd ../..

      - name: Build main application
        run: mvn clean package

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM validate
        run: sam validate

      - name: SAM build
        run: sam build

      - name: SAM deploy
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name photo-blog-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --resolve-s3 \
            --parameter-overrides \
              Stage=${{ secrets.ENVIRONMENT }} \
              DatasourceUsername="${{ secrets.DATASOURCE_USERNAME }}" \
              DatasourceUrl="${{ secrets.DATASOURCE_URL }}" \
              DatasourcePassword="${{ secrets.DATASOURCE_PASSWORD }}" \
              ImageKitUrlEndpoint="${{ secrets.IMAGEKIT_URL_ENDPOINT }}" \
              ImageKitPrivateKey="${{ secrets.IMAGEKIT_PRIVATE_KEY }}" \
              ImageKitPublicKey="${{ secrets.IMAGEKIT_PUBLIC_KEY }}"
